[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "max-age=2592000"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "max-age=31536000"
